# Generated by Django 4.0.6 on 2022-07-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urzadzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=100)),
                ('Opis', models.TextField(blank=True)),
                ('Numer_inwentarzowy', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
