# Generated by Django 4.0.6 on 2022-07-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urzadzenia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numer_laboratorium', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Laboratorium',
                'verbose_name_plural': 'Laboratoria',
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imię_i_Nazwisko', models.CharField(default='', max_length=30)),
                ('Dodatkowe_informmacja', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Osoba odpowiedzialna',
                'verbose_name_plural': 'Osoby odpowiedzialne',
            },
        ),
        migrations.AlterModelOptions(
            name='urzadzenia',
            options={'verbose_name': 'Urządzenie', 'verbose_name_plural': 'Urządzenia'},
        ),
        migrations.AddField(
            model_name='urzadzenia',
            name='Numer_laboratorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Urzadzenia.laboratorium'),
        ),
        migrations.AddField(
            model_name='urzadzenia',
            name='Osoba_odpowiedzialna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Urzadzenia.osoba'),
        ),
    ]
