# Generated by Django 4.0.6 on 2022-08-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urzadzenia', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Nazwa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Urzadzenia.urzadzenia'),
        ),
    ]
